"""LLM-based deduplication for image caption and OCR text."""

from __future__ import annotations

import asyncio
import logging
import re
from typing import Any

from ...core.config import settings
from ...core.metrics import VISION_DEDUP_FAILURES_TOTAL
from .. import llm as llm_service

logger = logging.getLogger(__name__)

# Precompiled pattern for digits (signals OCR has concrete data)
_HAS_DIGIT_RE = re.compile(r"\d")


def _normalize_text(value: str | None) -> str | None:
    if not isinstance(value, str):
        return None
    normalized = value.strip()
    return normalized or None


async def deduplicate_caption_ocr(
    caption: str | None, ocr_text: str | None
) -> tuple[str | None, str | None]:
    """Use LLM to decide whether caption and OCR are semantically duplicate.

    Returns a tuple of `(caption, ocr_text)` after deduplication.
    """
    normalized_caption = _normalize_text(caption)
    normalized_ocr = _normalize_text(ocr_text)
    if not normalized_caption or not normalized_ocr:
        return normalized_caption, normalized_ocr
    if not settings.MULTIMODAL_CAPTION_OCR_DEDUP_ENABLED:
        return normalized_caption, normalized_ocr
    if normalized_caption.casefold() == normalized_ocr.casefold():
        return normalized_caption, None

    # Heuristic short-circuit: if OCR contains digits or OCR is much longer
    # than caption, the two signals are clearly complementary — skip LLM call.
    if _HAS_DIGIT_RE.search(normalized_ocr):
        return normalized_caption, normalized_ocr
    caption_len = max(len(normalized_caption), 1)
    if len(normalized_ocr) / caption_len > 2.0:
        return normalized_caption, normalized_ocr

    prompt = (
        "You are judging if two texts about the same image are redundant.\n"
        "- caption: concise visual description generated by a vision model.\n"
        "- ocr_text: text recognized/extracted from image/document content.\n\n"
        "If OCR contains distinct text details (numbers, names, labels, visible words)\n"
        "not in caption, they are NOT duplicates.\n"
        "If both mostly express the same semantic content, treat as duplicates.\n\n"
        "Return strict JSON only:\n"
        '{"duplicate": true|false, "keep": "caption"|"ocr"|"both"}\n\n'
        f"caption:\n{normalized_caption}\n\n"
        f"ocr_text:\n{normalized_ocr}\n"
    )

    try:
        llm = llm_service.get_llm()
        response: Any = await asyncio.wait_for(
            llm.ainvoke(prompt),
            timeout=settings.MULTIMODAL_CAPTION_OCR_DEDUP_TIMEOUT_SECONDS,
        )
        raw = response.content if hasattr(response, "content") else str(response)
        parsed = llm_service.parse_llm_json(str(raw))
    except Exception:
        VISION_DEDUP_FAILURES_TOTAL.inc()
        logger.warning("Caption/OCR dedupe LLM call failed; keeping both fields", exc_info=True)
        return normalized_caption, normalized_ocr

    if not isinstance(parsed, dict):
        return normalized_caption, normalized_ocr
    if not bool(parsed.get("duplicate")):
        return normalized_caption, normalized_ocr

    keep = str(parsed.get("keep", "both")).strip().lower()
    if keep == "caption":
        return normalized_caption, None
    if keep == "ocr":
        return None, normalized_ocr
    return normalized_caption, normalized_ocr
