"""Settings GET endpoint and helpers."""

from ....core.config import settings
from ....models.schemas import (
    ASRSettings,
    EmbeddingSettings,
    LLMSettings,
    MemorySettings,
    OCRSettings,
    ParserSettings,
    RAGSettings,
    RetentionSettings,
    SearchSettings,
    ServerInfo,
    SettingsResponse,
    TTSSettings,
    UploadSettings,
    VisionSettings,
)
from ._common import _normalize_retriever_provider, router


def _mask_secret(value: str | None) -> str:
    """Mask API keys for safe display: fixed placeholder to avoid leaking any characters."""
    if not value:
        return ""
    return "***"


def _get_current_settings() -> SettingsResponse:
    """Build settings response from current configuration."""
    return SettingsResponse(
        llm=LLMSettings(
            binding=settings.LLM_BINDING,
            model=settings.LLM_MODEL,
            api_key=_mask_secret(settings.LLM_API_KEY.get_secret_value()),
            base_url=settings.LLM_BASE_URL,
            host=settings.LLM_HOST,
            temperature=settings.LLM_TEMPERATURE,
            max_tokens=settings.LLM_MAX_TOKENS,
        ),
        embedding=EmbeddingSettings(
            binding=settings.EMBEDDING_BINDING,
            model=settings.EMBEDDING_MODEL,
            api_key=_mask_secret(settings.EMBEDDING_API_KEY.get_secret_value()),
            base_url=settings.EMBEDDING_BASE_URL,
            host=settings.EMBEDDING_HOST,
            dimension=settings.EMBEDDING_DIMENSION,
        ),
        rag=RAGSettings(
            chunk_size=settings.CHUNK_SIZE,
            chunk_overlap=settings.CHUNK_OVERLAP,
            top_k=settings.TOP_K,
            query_rewrite_enabled=settings.QUERY_REWRITE_ENABLED,
            query_rewrite_model=settings.QUERY_REWRITE_MODEL,
            score_threshold=settings.SCORE_THRESHOLD,
            distance_metric=settings.DISTANCE_METRIC,
            reranker_binding=settings.RERANKER_BINDING,
            reranker_model=settings.RERANKER_MODEL,
            reranker_api_key=_mask_secret(settings.RERANKER_API_KEY.get_secret_value()),
            reranker_base_url=settings.RERANKER_BASE_URL,
            reranker_top_n=settings.RERANKER_TOP_N,
            reranker_min_score=settings.RERANKER_MIN_SCORE,
            reranker_timeout_seconds=settings.RERANKER_TIMEOUT_SECONDS,
            fetch_multiplier=settings.RAG_RERANK_FETCH_MULTIPLIER,
            persist_interval_seconds=settings.RAG_PERSIST_INTERVAL_SECONDS,
            parent_child_enabled=settings.PARENT_CHILD_ENABLED,
            child_chunk_size=settings.CHILD_CHUNK_SIZE,
            child_chunk_overlap=settings.CHILD_CHUNK_OVERLAP,
            hybrid_search_enabled=settings.HYBRID_SEARCH_ENABLED,
            hybrid_alpha=settings.HYBRID_ALPHA,
            retriever_provider=_normalize_retriever_provider(settings.RAG_RETRIEVER_PROVIDER),
            raganything_enabled=settings.RAGANYTHING_ENABLED,
            raganything_fallback_to_native=settings.RAGANYTHING_FALLBACK_TO_NATIVE,
            raganything_working_dir=settings.RAGANYTHING_WORKING_DIR,
            raganything_index_timeout_seconds=settings.RAGANYTHING_INDEX_TIMEOUT_SECONDS,
            raganything_query_timeout_seconds=settings.RAGANYTHING_QUERY_TIMEOUT_SECONDS,
            raganything_llm_timeout_seconds=settings.RAGANYTHING_LLM_TIMEOUT_SECONDS,
            semantic_chunking_enabled=settings.SEMANTIC_CHUNKING_ENABLED,
            non_text_chunking_strategy=settings.NON_TEXT_CHUNKING_STRATEGY,
            multi_query_enabled=settings.MULTI_QUERY_ENABLED,
            multi_query_count=settings.MULTI_QUERY_COUNT,
            index_tables=settings.RAG_INDEX_TABLES,
            index_image_captions=settings.RAG_INDEX_IMAGE_CAPTIONS,
            image_ocr_min_length=settings.RAG_IMAGE_OCR_MIN_LENGTH,
            content_type_rerank_enabled=settings.RAG_CONTENT_TYPE_RERANK_ENABLED,
            sibling_coretrieve_enabled=settings.RAG_SIBLING_CORETRIEVE_ENABLED,
            sibling_coretrieve_per_anchor=settings.RAG_SIBLING_CORETRIEVE_PER_ANCHOR,
            sibling_coretrieve_max_total=settings.RAG_SIBLING_CORETRIEVE_MAX_TOTAL,
            audio_semantic_boundary_enabled=settings.AUDIO_SEMANTIC_BOUNDARY_ENABLED,
            audio_semantic_boundary_threshold=settings.AUDIO_SEMANTIC_BOUNDARY_THRESHOLD,
            audio_semantic_min_segments=settings.AUDIO_SEMANTIC_MIN_SEGMENTS,
            audio_semantic_max_segments=settings.AUDIO_SEMANTIC_MAX_SEGMENTS,
            speaker_in_content=settings.AUDIO_SPEAKER_IN_CONTENT,
            split_on_speaker_change=settings.AUDIO_SPLIT_ON_SPEAKER_CHANGE,
        ),
        memory=MemorySettings(
            auto_extract=settings.MEMORY_AUTO_EXTRACT,
            max_facts_per_turn=settings.MEMORY_MAX_FACTS_PER_TURN,
            decay_enabled=settings.MEMORY_DECAY_ENABLED,
            decay_interval_hours=settings.MEMORY_DECAY_INTERVAL_HOURS,
            ttl_days=settings.MEMORY_TTL_DAYS,
            session_max_history=settings.SESSION_MAX_HISTORY,
            max_context_items=settings.MEMORY_MAX_CONTEXT_ITEMS,
            session_max_tokens=settings.SESSION_MAX_TOKENS,
            session_summary_enabled=settings.SESSION_SUMMARY_ENABLED,
            session_summary_min_turns=settings.SESSION_SUMMARY_MIN_TURNS,
            session_summary_max_items=settings.SESSION_SUMMARY_MAX_ITEMS,
            session_summary_max_messages=settings.SESSION_SUMMARY_MAX_MESSAGES,
            session_summary_idle_minutes=settings.SESSION_SUMMARY_IDLE_MINUTES,
            session_summary_startup_backfill=settings.SESSION_SUMMARY_STARTUP_BACKFILL,
            consolidation_enabled=settings.MEMORY_CONSOLIDATION_ENABLED,
            consolidation_min_cluster=settings.MEMORY_CONSOLIDATION_MIN_CLUSTER,
            semantic_cluster_enabled=settings.MEMORY_SEMANTIC_CLUSTER_ENABLED,
            knowledge_graph_enabled=settings.KNOWLEDGE_GRAPH_ENABLED,
            profile_enabled=settings.MEMORY_PROFILE_ENABLED,
            profile_refresh_interval=settings.MEMORY_PROFILE_REFRESH_INTERVAL,
            extraction_mode=settings.MEMORY_EXTRACTION_MODE,
            entity_relations_limit=settings.ENTITY_RELATIONS_LIMIT,
            global_memory_limit=settings.GLOBAL_MEMORY_LIMIT,
            skip_threshold=settings.SESSION_CONTEXT_SKIP_THRESHOLD,
        ),
        search=SearchSettings(
            binding=settings.SEARCH_BINDING,
            api_key=_mask_secret(settings.SEARCH_API_KEY.get_secret_value()),
            region=settings.SEARCH_REGION,
            max_results=settings.SEARCH_MAX_RESULTS,
            timeout=settings.SEARCH_TIMEOUT,
            web_search_timeout_s=settings.WEB_SEARCH_TIMEOUT_S,
        ),
        upload=UploadSettings(
            max_size_mb=settings.MAX_UPLOAD_SIZE_MB,
            auto_summarize_files=settings.MEETING_AUTO_SUMMARIZE_FILES,
            multimodal_captioning_enabled=settings.MULTIMODAL_CAPTIONING_ENABLED,
            ocr_dedup_enabled=settings.MULTIMODAL_CAPTION_OCR_DEDUP_ENABLED,
            ocr_dedup_timeout_seconds=settings.MULTIMODAL_CAPTION_OCR_DEDUP_TIMEOUT_SECONDS,
            video_keyframes_enabled=settings.VIDEO_KEYFRAMES_ENABLED,
        ),
        asr=ASRSettings(
            provider=settings.ASR_PROVIDER,
            language=settings.ASR_LANGUAGE,
            assemblyai_api_key=_mask_secret(settings.ASSEMBLYAI_API_KEY.get_secret_value()),
            speech_model=settings.ASSEMBLYAI_SPEECH_MODEL,
            speaker_labels=settings.ASSEMBLYAI_SPEAKER_LABELS,
            language_detection=settings.ASSEMBLYAI_LANGUAGE_DETECTION,
            poll_interval_seconds=settings.ASSEMBLYAI_POLL_INTERVAL_SECONDS,
            max_wait_seconds=settings.ASSEMBLYAI_MAX_WAIT_SECONDS,
        ),
        ocr=OCRSettings(
            provider=settings.OCR_PROVIDER,
            language=settings.OCR_LANGUAGE,
            dpi=settings.OCR_DPI,
            marker_base_url=settings.MARKER_BASE_URL,
            marker_api_key=_mask_secret(settings.MARKER_API_KEY.get_secret_value()),
            marker_max_wait_seconds=settings.MARKER_MAX_WAIT_SECONDS,
            mineru_base_url=settings.MINERU_BASE_URL,
            mineru_api_key=_mask_secret(settings.MINERU_API_KEY.get_secret_value()),
            mineru_max_wait_seconds=settings.MINERU_MAX_WAIT_SECONDS,
            paddleocr_base_url=settings.PADDLEOCR_BASE_URL,
            paddleocr_api_key=_mask_secret(settings.PADDLEOCR_API_KEY.get_secret_value()),
            http_timeout_seconds=settings.PARSER_HTTP_TIMEOUT_SECONDS,
            poll_interval_seconds=settings.PARSER_POLL_INTERVAL_SECONDS,
        ),
        vision=VisionSettings(
            model=settings.VISION_MODEL,
            api_key=_mask_secret(settings.VISION_API_KEY.get_secret_value()),
            base_url=settings.VISION_BASE_URL,
            retry_max_attempts=settings.VISION_RETRY_MAX_ATTEMPTS,
            retry_base_delay_seconds=settings.VISION_RETRY_BASE_DELAY_SECONDS,
            retry_max_delay_seconds=settings.VISION_RETRY_MAX_DELAY_SECONDS,
            caption_min_chars=settings.VISION_CAPTION_MIN_CHARS,
            ocr_min_chars=settings.VISION_OCR_MIN_CHARS,
        ),
        tts=TTSSettings(
            binding=settings.TTS_BINDING,
            model=settings.TTS_MODEL,
            api_key=_mask_secret(settings.TTS_API_KEY.get_secret_value()),
            base_url=settings.TTS_BASE_URL,
            voice=settings.TTS_VOICE,
            speed=settings.TTS_SPEED,
        ),
        parser=ParserSettings(
            max_parse_pages=settings.MAX_PARSE_PAGES,
            parse_timeout_seconds=settings.PARSE_TIMEOUT_SECONDS,
            timeout_per_mb_seconds=settings.PARSE_TIMEOUT_PER_MB_SECONDS,
            timeout_max_seconds=settings.PARSE_TIMEOUT_MAX_SECONDS,
            max_images_per_page=settings.PARSER_MAX_IMAGES_PER_PAGE,
            max_image_bytes=settings.PARSER_MAX_IMAGE_BYTES,
            doc_clean_repetition_min_pages=settings.DOC_CLEAN_REPETITION_MIN_PAGES,
            doc_clean_repetition_min_ratio=settings.DOC_CLEAN_REPETITION_MIN_RATIO,
            doc_clean_header_footer_max_lines=settings.DOC_CLEAN_HEADER_FOOTER_MAX_LINES,
            doc_clean_repetition_max_line_length=settings.DOC_CLEAN_REPETITION_MAX_LINE_LENGTH,
        ),
        retention=RetentionSettings(
            chat_message_retention_days=settings.CHAT_MESSAGE_RETENTION_DAYS,
            decay_state_retention_days=settings.DECAY_STATE_RETENTION_DAYS,
        ),
        server=ServerInfo(
            environment=settings.ENVIRONMENT,
            host=settings.HOST,
            port=settings.PORT,
            cors_origins=settings.CORS_ORIGINS,
            trusted_proxies=settings.TRUSTED_PROXIES,
            trusted_hosts=settings.TRUSTED_HOSTS,
            security_headers_enabled=settings.SECURITY_HEADERS_ENABLED,
            security_hsts_max_age=settings.SECURITY_HSTS_MAX_AGE,
            security_frame_options=settings.SECURITY_FRAME_OPTIONS,
            security_referrer_policy=settings.SECURITY_REFERRER_POLICY,
            security_csp=settings.SECURITY_CSP,
        ),
    )


@router.get("", response_model=SettingsResponse)
async def get_settings() -> SettingsResponse:
    """Get current application configuration settings."""
    return _get_current_settings()
