/**
 * Shared Markdown + LaTeX rendering configuration.
 *
 * All ReactMarkdown instances should use these plugin arrays
 * so that `$...$` and `$$...$$` math syntax is rendered by KaTeX.
 */

import rehypeKatex from "rehype-katex";
import rehypeSanitize, { defaultSchema } from "rehype-sanitize";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import type { PluggableList } from "unified";

// Katex CSS is imported here for code colocation — the synchronous rehypePlugins
// exports below depend on KaTeX styling.  The CSS import is kept at module level
// because most markdown renderers in the app use the synchronous path.
import "katex/dist/katex.min.css";

/**
 * Rehype-sanitize schema extended to allow math elements generated by remark-math / rehype-katex.
 *
 * KaTeX produces `<span class="katex">` wrappers and `<math>` elements with
 * `<annotation>` children.  The default sanitize schema strips these, so we
 * explicitly allow them.  Style and className on math sub-elements are restricted
 * to prevent CSS-based data exfiltration.
 */
const MATH_STYLE_ATTR = "style";
const KATEX_CLASSNAME_RE =
  /^(katex|katex-.+|mfrac|sizing|sizing-.+|nulldelimiter|delimsizing|mord|mop|mbin|mrel|mopen|mclose|mpunct|minner|mstyle|vlist-t|vlist-r|vlist-s|mspace|strut|reset-size|size1|size2|size3|size4|size5|size6|size7|size8|size9|size10|fontsize-ensurer|cbstyle|mstart|mend|baseline-fix|llap|rlap|frac-line|sqrt-sign|sqrt-line|mroot|mover|munder|munderover|mtable|mtr|mtd|mlabeledtr|maligngroup|malignmark|mprescripts|none)$/;

const mathSafeSchema: NonNullable<Parameters<typeof rehypeSanitize>[0]> = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    // Only allow className globally; style is restricted to KaTeX math elements below.
    "*": [...(defaultSchema.attributes?.["*"] ?? []), "className"],
    span: [...(defaultSchema.attributes?.span ?? []), "className", MATH_STYLE_ATTR, "aria-hidden"],
    math: [...(defaultSchema.attributes?.math ?? []), "xmlns", "display", "mathvariant"],
    annotation: [...(defaultSchema.attributes?.annotation ?? []), "encoding"],
    mrow: [
      ...(defaultSchema.attributes?.mrow ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mi: [...(defaultSchema.attributes?.mi ?? []), "mathvariant"],
    mn: [...(defaultSchema.attributes?.mn ?? []), "mathvariant"],
    mo: [...(defaultSchema.attributes?.mo ?? []), "mathvariant"],
    msup: [
      ...(defaultSchema.attributes?.msup ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    msub: [
      ...(defaultSchema.attributes?.msub ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mfrac: [
      ...(defaultSchema.attributes?.mfrac ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    msqrt: [
      ...(defaultSchema.attributes?.msqrt ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mtext: [
      ...(defaultSchema.attributes?.mtext ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mspace: [
      ...(defaultSchema.attributes?.mspace ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mstyle: [
      ...(defaultSchema.attributes?.mstyle ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    menclose: [
      ...(defaultSchema.attributes?.menclose ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mpadded: [
      ...(defaultSchema.attributes?.mpadded ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mphantom: [
      ...(defaultSchema.attributes?.mphantom ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mtable: [
      ...(defaultSchema.attributes?.mtable ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mtr: [
      ...(defaultSchema.attributes?.mtr ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    mtd: [
      ...(defaultSchema.attributes?.mtd ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
    semantics: [
      ...(defaultSchema.attributes?.semantics ?? []),
      MATH_STYLE_ATTR,
      ["className", KATEX_CLASSNAME_RE],
    ],
  },
  tagNames: [
    ...(defaultSchema.tagNames ?? []),
    "math",
    "annotation",
    "semantics",
    "mrow",
    "mi",
    "mn",
    "mo",
    "msup",
    "msub",
    "mfrac",
    "msqrt",
    "mtext",
    "mspace",
    "mstyle",
    "menclose",
    "mpadded",
    "mphantom",
    "mtable",
    "mtr",
    "mtd",
  ],
  strip: ["script"],
};

/** Remark plugins — parse math fences before rehype conversion. */
export const remarkPlugins: PluggableList = [remarkGfm, remarkMath];

/** Check whether content likely contains LaTeX math delimiters. */
export function hasMathContent(text: string): boolean {
  return /\$[^$]+\$|\$\$[\s\S]*?\$\$/.test(text);
}

/** Rehype plugins without KaTeX — used when content has no math. */
export const rehypePluginsNoMath: PluggableList = [[rehypeSanitize, mathSafeSchema]];

/** Build rehype plugins with KaTeX loaded dynamically only when math is detected. */
export async function getRehypePlugins(text: string): Promise<PluggableList> {
  if (!hasMathContent(text)) {
    return rehypePluginsNoMath;
  }
  const { default: katexPlugin } = await import("rehype-katex");
  return [katexPlugin, [rehypeSanitize, mathSafeSchema]];
}

/** Synchronous rehype plugins with KaTeX. Prefer getRehypePlugins() for dynamic loading. */
export const rehypePlugins: PluggableList = [rehypeKatex, [rehypeSanitize, mathSafeSchema]];

/** Normalize LaTeX \\(...\\)/\\[...\\] delimiters into Markdown math syntax. */
export const normalizeLatexMathDelimiters = (input: string): string => {
  const displayReplaced = input.replace(/\\\[([\s\S]*?)\\\]/g, (_, expr: string) => {
    const content = expr.trim();
    if (!content) return "$$$$";
    return `$$\n${content}\n$$`;
  });
  return displayReplaced.replace(/\\\(([\s\S]*?)\\\)/g, (_, expr: string) => {
    const content = expr.trim();
    return content ? `$${content}$` : "$$";
  });
};

const STORAGE_ASSET_PREFIXES = [
  "meeting_assets/",
  "/meeting_assets/",
  "uploads/meeting_assets/",
  "/uploads/meeting_assets/",
];

const toStoragePath = (rawSrc: string): string | null => {
  const trimmed = rawSrc.trim();
  if (!trimmed) return null;
  const stripped =
    trimmed.startsWith("<") && trimmed.endsWith(">") ? trimmed.slice(1, -1) : trimmed;
  const withoutHash = stripped.split("#", 1)[0];
  const withoutQuery = withoutHash.split("?", 1)[0];
  for (const prefix of STORAGE_ASSET_PREFIXES) {
    if (!withoutQuery.startsWith(prefix)) continue;
    return withoutQuery.replace(/^\/?uploads\//, "").replace(/^\/+/, "");
  }
  return null;
};

/** Resolve markdown image src values to authenticated `/meetings/assets` URLs when possible.

Returns `undefined` when the src cannot be resolved to a known asset path.
Callers should render nothing (return `null`) when the result is `undefined`
to avoid broken `<img>` tags from parser-generated relative paths.
*/
export const resolveMarkdownImageSrc = (
  src: string | undefined,
  resolveAssetUrl: (storagePath: string) => string,
): string | undefined => {
  if (!src) return src;
  const trimmed = src.trim();
  if (!trimmed) return src;
  const lower = trimmed.toLowerCase();
  // Only allow data: URIs with image/ MIME types; reject blob: and non-image data: URIs.
  if (lower.startsWith("data:") && !lower.startsWith("data:image/")) return "data:,";
  if (lower.startsWith("blob:")) return "data:,";

  try {
    const absolute = new URL(trimmed, window.location.origin);
    if (absolute.pathname.endsWith("/meetings/assets")) return absolute.toString();
  } catch {
    // Ignore parse errors and continue with storage-path parsing.
  }

  const storagePath = toStoragePath(trimmed);
  // FE-14: Return empty data URI instead of undefined to avoid <img src="undefined">.
  if (!storagePath) return "data:,";
  return resolveAssetUrl(storagePath);
};
